const Dummydata = {
  quantity: 0,
  NameofPurchaser: "",
  Registration_No: "",
  VehicleCapacity: 0,
  VehicleType: "",
  PurchaserAdd: "",
  PurchaserDristic: "",
  PoliceStation: "",
  PurchaserMobileNo: "",
  IssueDate: "",
  ValidityDate: "",
  PurchaseDristic: "",
  GeneratedDT: "",
  EchallanId: 0,
  VehicleQunText:"",
  PrintButtonEnable: false,
  RoyaltyOwners: {
    id: 1,
    OwnerName: "",
    SandID: "",
    VidePermitNo: "",
    EChallanId: "",
    OwnerAddress: "",
    OwnerAddressLine1: "",
    OwnerAddressLine2: "",
    OwnerMobileNo: "",
    OwnerMouza: "",
    OwnerDistrict: "",
    OwnerPoliceStation: "",
    OwnerGpWard: "",
    River: "",
    OwnerSubDivision: "",
  },
};

export default Dummydata;
