export const gstStateCodes = {
    "andaman_nicobar": { code: 35 },
    "andhra_pradesh": { code: 37 },
    "arunachal_pradesh": { code: 12 },
    "assam": { code: 18 },
    "bihar": { code: 10 },
    "chandigarh": { code: 4 },
    "chhattisgarh": { code: 22 },
    "dadra_nagar_haveli_daman_diu": { code: 26 }, // Merged UT
    "delhi": { code: 7 },
    "goa": { code: 30 },
    "gujarat": { code: 24 },
    "haryana": { code: 6 },
    "himachal_pradesh": { code: 2 },
    "jammu_kashmir": { code: 1 },
    "jharkhand": { code: 20 },
    "karnataka": { code: 29 },
    "kerala": { code: 32 },
    "ladakh": { code: 38 },
    "lakshadweep": { code: 31 },
    "madhya_pradesh": { code: 23 },
    "maharashtra": { code: 27 },
    "manipur": { code: 14 },
    "meghalaya": { code: 17 },
    "mizoram": { code: 15 },
    "nagaland": { code: 13 },
    "odisha": { code: 21 },
    "puducherry": { code: 34 },
    "punjab": { code: 3 },
    "rajasthan": { code: 8 },
    "sikkim": { code: 11 },
    "tamil_nadu": { code: 33 },
    "telangana": { code: 36 },
    "tripura": { code: 16 },
    "uttar_pradesh": { code: 9 },
    "uttarakhand": { code: 5 },
    "west_bengal": { code: 19 }
};

export default gstStateCodes;
